# Request the device information from the device.


---
# The name of the device
string device_name

# The serial number of the device
string serial_number

# The firmware version of the device
string firmware_version

# The host version of the device
string host_version
